apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restauranty-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - restauranty.az.ironlabs.online
    secretName: restauranty-tls-secret
  - hosts:
    - grafana.az.ironlabs.online
    secretName: grafana-tls-secret
  rules:
  - host: restauranty.az.ironlabs.online
    http:
      paths:
      - path: /api/auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 3001
      - path: /api/discounts(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: discounts-service
            port:
              number: 3002
      - path: /api/items(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: items-service
            port:
              number: 3003
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  - host: grafana.az.ironlabs.online
    http:
      paths:
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: monitoring-grafana
            port:
              number: 80
